//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFmpegWrapperCore.FFmpegArguments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FFmpegArgsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FFmpegArgsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFmpegWrapperCore.FFmpegArguments.FFmpegArgsResources", typeof(FFmpegArgsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ArgSeparator {
            get {
                return ResourceManager.GetString("ArgSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -ast {0}.
        /// </summary>
        internal static string AudioStreamSpecifier {
            get {
                return ResourceManager.GetString("AudioStreamSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -showmode 1.
        /// </summary>
        internal static string AudioWavesShowMode {
            get {
                return ResourceManager.GetString("AudioWavesShowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -disposition:{0}:{1} {2}.
        /// </summary>
        internal static string DefaultStreamArgument {
            get {
                return ResourceManager.GetString("DefaultStreamArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -itsoffset {0}.
        /// </summary>
        internal static string DelayArgument {
            get {
                return ResourceManager.GetString("DelayArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -v error -show_format -of json=c=1 -show_streams &quot;{0}&quot;.
        /// </summary>
        internal static string FileInfo {
            get {
                return ResourceManager.GetString("FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -i &quot;{0}&quot;.
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -map {0}:{1}:{2}.
        /// </summary>
        internal static string MapArgument {
            get {
                return ResourceManager.GetString("MapArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}{3}-c copy &quot;{4}&quot;.
        /// </summary>
        internal static string MergeArgument {
            get {
                return ResourceManager.GetString("MergeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &quot;{0}&quot;.
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -metadata:s:{0}:{1} {2}=&quot;{3}&quot;.
        /// </summary>
        internal static string StreamMetadataArgument {
            get {
                return ResourceManager.GetString("StreamMetadataArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -sst {0}.
        /// </summary>
        internal static string SubtitleStreamSpecifier {
            get {
                return ResourceManager.GetString("SubtitleStreamSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -vst {0}.
        /// </summary>
        internal static string VideoStreamSpecifier {
            get {
                return ResourceManager.GetString("VideoStreamSpecifier", resourceCulture);
            }
        }
    }
}
