//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFmpegWrapperCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFmpegWrapperCore.LibResources", typeof(LibResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;code&quot;: &quot;aar&quot;,
        ///    &quot;language&quot;: &quot;Afar&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;abk&quot;,
        ///    &quot;language&quot;: &quot;Abkhazian&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;ace&quot;,
        ///    &quot;language&quot;: &quot;Achinese&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;ach&quot;,
        ///    &quot;language&quot;: &quot;Acoli&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;ada&quot;,
        ///    &quot;language&quot;: &quot;Adangme&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;ady&quot;,
        ///    &quot;language&quot;: &quot;Adyghe; Adygei&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;afa&quot;,
        ///    &quot;language&quot;: &quot;Afro-Asiatic languages&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;afh&quot;,
        ///    &quot;language&quot;: &quot;Afrihili&quot;
        ///  },
        ///  {
        ///    &quot;code&quot;: &quot;afr&quot;,
        ///    &quot;language&quot;: &quot;Afrikaans&quot;
        ///  },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Languages_ISO_639_2 {
            get {
                return ResourceManager.GetString("Languages_ISO_639_2", resourceCulture);
            }
        }
    }
}
